--liquibase formatted sql
--changeset ism:create-new-users

CREATE TABLE tasks
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(256) NOT NULL,
    description VARCHAR(256),
    status      VARCHAR(256) not null check (status in ('IN_WAITING', 'IN_PROGRESS', 'COMPLETED')),
    priority    VARCHAR(256) not null check (priority in ('HIGH', 'MEDIUM', 'LOW')),
    author_id   BIGINT,
    CONSTRAINT fk_author FOREIGN KEY (author_id) REFERENCES users (id)
);

CREATE TABLE performers_users
(
    task_id BIGINT,
    user_id BIGINT,
    CONSTRAINT fk_performers_users FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE CASCADE,
    CONSTRAINT fk_users_performers FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    PRIMARY KEY (task_id, user_id)
);

CREATE TABLE comments
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    text       VARCHAR(256) NOT NULL,
    FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE CASCADE,
    FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE
);
