--liquibase formatted sql
--changeset ism:create-tables

CREATE TABLE users(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(256) NOT NULL UNIQUE,
    password VARCHAR(256) NOT NULL,
    role VARCHAR(256) not null check (role in ('ROLE_USER','ROLE_ADMIN'))
)